name: EditorConfig

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  lint:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - name: editorconfig-checker
        run: |
          echo "::add-matcher::.github/workflows/editorconfig-checker.matcher.json"
          scripts/editorconfig-checker.bat
