name: "Editor Config Checker"

on:
  pull_request:
  push:
    branches:
      - master
      - main
      - develop

jobs:
  lint:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: editorconfig-checker
        run: scripts/editorconfig-checker.bat
