name: "Pull Request Nightly Build"

on:
  pull_request:

env:
  SOLUTION_PATH: .
  BUILD_CONFIGURATION: DevBuild
  ARTIFACT_NAME: CnCNet-Spawner_${{ github.ref_name }}.zip

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build
        uses: ./.github/actions/build
        with:
          sln-path: ${{ env.SOLUTION_PATH }}
          build-config: ${{ env.BUILD_CONFIGURATION }}
          artifact-name: compiled-dll-regular-${{ github.sha }}

      - name: Build HardEnd
        uses: ./.github/actions/build
        with:
          sln-path: ${{ env.SOLUTION_PATH }}
          build-config: ${{ env.BUILD_CONFIGURATION }}-HardEnd
          artifact-name: compiled-dll-hardend-${{ github.sha }}
